# Generated by Django 4.2.20 on 2025-04-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HandTrackingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user", models.CharField(max_length=100)),
                ("hand_detected", models.BooleanField(default=False)),
            ],
        ),
    ]
